=== AnubhavBala/MiringValidator/src/main/resources/schema/RuleTemplate.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- 

    MiringValidator  Semantic Validator for MIRING compliant HML
    Copyright (c) 2015 National Marrow Donor Program (NMDP)

    This library is free software; you can redistribute it and/or modify it
    under the terms of the GNU Lesser General Public License as published
    by the Free Software Foundation; either version 3 of the License, or (at
    your option) any later version.

    This library is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; with out even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
    License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with this library;  if not, write to the Free Software Foundation,
    Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA.

    > http://www.gnu.org/licenses/lgpl.html

 -->
 
<xs:schema attributeFormDefault="unqualified" 
  elementFormDefault="qualified" 
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="RuleTemplate">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Rule" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="miringRuleID"  use="required"/>
                <xs:attribute type="xs:string" name="severity"      use="required"/>
                <xs:attribute type="xs:string" name="errorMessage"  use="optional"/>
                <xs:attribute type="xs:string" name="solutionText"  use="optional"/>
                <xs:attribute type="xs:string" name="nodeName"      use="optional"/>
                <xs:attribute type="xs:string" name="attributeName" use="optional"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AnubhavBala/MiringValidator/src/main/resources/ruletemplates/SchematronRuleTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 

    MiringValidator  Semantic Validator for MIRING compliant HML
    Copyright (c) 2015 National Marrow Donor Program (NMDP)

    This library is free software; you can redistribute it and/or modify it
    under the terms of the GNU Lesser General Public License as published
    by the Free Software Foundation; either version 3 of the License, or (at
    your option) any later version.

    This library is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; with out even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
    License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with this library;  if not, write to the Free Software Foundation,
    Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA.

    > http://www.gnu.org/licenses/lgpl.html

 -->
 
<RuleTemplate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../schema/RuleTemplate.xsd">

  <Rule errorMessage="The hmlid root is formatted like an OID." 
    miringRuleID="1.1.c" 
    solutionText="No solution needed.  This is a good thing." 
    severity="info" />
    
  <Rule errorMessage="The hmlid root is not formatted like an OID." 
    miringRuleID="1.1.c" 
    solutionText="Please format the hmlid node's root attribute like an OID:  11.234.55555.65" 
    severity="info" />

  <Rule errorMessage="On a sbt-ngs node, test-id is not formatted like a GTR test ID." 
    miringRuleID="1.3.b" 
    solutionText="Other test formats are allowed. It isn't necessary to only use a GTR test ID: GTR000000000.0" 
    severity="info" />

  <Rule errorMessage="On a sbt-ngs node, the test-id-source is not explicitly 'NCBI-GTR'." 
    miringRuleID="1.3.b" 
    solutionText="Other options are allowed. It isn't necessary to only use NCBI-GTR'" 
    severity="info" />

  <Rule errorMessage="On a reference sequence node, end attribute should be greater than or equal to the start attribute." 
    miringRuleID="2.2.c" 
    solutionText="The end attribute should be greater than or equal to the start attribute." 
    severity="miring" />

  <Rule errorMessage="A reference-sequence node has an id attribute with no corresponding consensus-sequence-block id attribute." 
    miringRuleID="2.2.1.c" 
    solutionText="This is a warning, not a serious error.  consensus-sequence-block:reference-sequence-id must have a corresponding reference-sequence:id, but the opposite is not necessarily true." 
    severity="warning" />
    
  <Rule errorMessage="On a sequence quality node, the sequence-start and sequence-end attributes must be between 0 and (consensus-sequence-block:end - consensus-sequence-block:start) inclusive." 
    miringRuleID="4.b" 
    solutionText="A sequence-quality node has a sequence-start and sequence-end attributes.  They refer to positions within the consensus-sequence-block, and therefore must be contained within the range of parent's end and start." 
    severity="miring" />

  <Rule errorMessage="The start attribute on a consensus-sequence-block node should be greater than or equal to the start attribute" 
    miringRuleID="4.2.3.d" 
    solutionText="Verify that the consensus-sequence-block:start is greater than or equal to start, and consensus-sequence-block:end is less than or equal to end on the corresponding reference-sequence." 
    severity="miring" />
    
  <Rule errorMessage="The end attribute on a consensus-sequence-block node should be less than or equal to the end attribute" 
    miringRuleID="4.2.3.d" 
    solutionText="Verify that the consensus-sequence-block:start is greater than or equal to start, and consensus-sequence-block:end is less than or equal to end on the corresponding reference-sequence." 
    severity="miring" />
    
  <Rule errorMessage="For every consensus-sequence-block node, the child sequence node must have a length of (end - start)." 
    miringRuleID="4.2.3.e" 
    solutionText="Please check the sequence length against the start and end attributes."
    severity="miring" />

  <Rule errorMessage="On a consensus-sequence-block node, the phasing-group attribute is deprecated." 
    miringRuleID="4.2.4.b" 
    solutionText="Please use phase-set instead." 
    severity="warning" />
    
  <Rule errorMessage="A consensus-sequence-block with attribute continuity=true does not appear to be continuous" 
    miringRuleID="4.2.7.b" 
    solutionText="Any consensus-sequence-block node with continuity=true is expected to be continuous with the previous sibling node.  Start=End(previous).  The previous node will have the same reference-sequence-id and phase-set, if applicable." 
    severity="miring" />
    
  <Rule errorMessage="On a variant node, end attribute should be greater than or equal to the start attribute" 
    miringRuleID="5.2.b" 
    solutionText="The end attribute should be greater than or equal to the start attribute." 
    severity="miring" />
    
  <Rule errorMessage="The start attribute on a variant node should be greater than or equal to the start attribute"
    miringRuleID="5.2.d"
    solutionText="Verify that variant:start is greater than or equal to the start, and variant:end is less than or equal to the end attribute on the corresponding reference-sequence." 
    severity="miring" />
    
  <Rule errorMessage="The end attribute on a variant node should be less than or equal to the end attribute"
    miringRuleID="5.2.d"
    solutionText="Verify that variant:start is greater than or equal to the start, and variant:end is less than or equal to the end attribute on the corresponding reference-sequence." 
    severity="miring" />
    
  <Rule errorMessage="The variant nodes under a single consensus-sequence-block must have id attributes that are integers ranging from 0:n-1, where n is the number of variants." 
    miringRuleID="5.3.c" 
    solutionText="IDs on variant nodes should start at 0, and represent every integer between 0:n-1." 
    severity="miring" />

</RuleTemplate>
